#!/bin/bash
if [ "${EUID}" -ne 0 ]; then
		echo "You need to run this script as root"
		exit 1
fi
if [ "$(systemd-detect-virt)" == "openvz" ]; then
		echo "OpenVZ is not supported"
		exit 1
fi
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
MYIP=$(wget -qO- icanhazip.com);
IZIN=$( curl https<>//raw.githubusercontent.com/Zeastore/gaspoll/main/ipvps | grep $MYIP )
if [ $MYIP = $IZIN ]; then
echo -e "${green}Permission Accepted...${NC}"
else
echo -e "${red}Permission Denied!${NC}";
echo "Please Contact Admin"
echo "Telegram not found"
rm -f setup.sh
exit 0
fi
clear
m="\033[0;1;36m"
y="\033[0;1;37m"
yy="\033[0;1;31m"
m1="\033[1;34m"
ISP=$(curl -s ipinfo.io/org | cut -d " " -f 2-10 )
CITY=$(curl -s ipinfo.io/city )
WKT=$(curl -s ipinfo.io/timezone )
IPVPS=$(curl -s ifconfig.me/ip )
echo -e ""
echo -e "ZEASTORE"
echo -e ""
echo -e "$m-----------------------------------------------------------------$y"
echo -e ""
echo -e "$m1 IP Vps                <> $IPVPS"
echo -e "$m1 Isp Vps Name <> $ISP"
echo -e "$m1 City                     <> $CITY"
echo -e "$m1 Waktu                <> $WKT"
echo -e ""
echo -e "$m=============================-$yy MENU $m-=============================$y"
echo -e ""
echo -e "* menu         <> List of Main Commands"
echo -e ""
echo -e "$m=========================-$yy SSH & OPENVPN $m-========================$y"
echo -e ""
echo -e "* 1.usernew    <> Create SSH & OpenVPN Account"
echo -e "* 2.trial             <> Generate SSH & OpenVPN Trial Account"
echo -e "* 3.renew         <> Extending SSH & OpenVPN Account Active Life"
echo -e "* 4.deluser       <> Delete SSH & OpenVPN Account"
echo -e "* 5.cek              <> Check User Login SSH & OpenVPN"
echo -e "* 6.member     <> Daftar Member SSH & OpenVPN"
echo -e "* 7.delete         <> Delete User Expired SSH & OpenVPN"
echo -e "* 8.autokill       <> Set up Autokill SSH"
echo -e "* 9.ceklim        <> Displays Users Who Do Multi Login SSH"
echo -e "* 10.restart        <> Restart Service Dropbear, Squid3, OpenVPN dan SSH"
echo -e ""
echo -e "$m===========================-$yy WIREGUARD $m-=========================$y"
echo -e ""
echo -e "* 11.add-wg       <> Create Wireguard Account"
echo -e "* 12.del-wg         <> Delete Wireguard Account"
echo -e "* 13.cek-wg        <> Check User Login Wireguard"
echo -e "* 14.renew-wg   <> Extending Wireguard Account Active Life"
echo -e "* 15.wg show     <> Check Wireguard User Interface"
echo -e ""
echo -e "$m=============================-$yy L2TP $m-============================$y"
echo -e ""
echo -e "* 16.add-l2tp      <> Creating L2TP Account"
echo -e "* 17.del-l2tp       <> Deleting L2TP Account"
echo -e "* 18.renew-l2tp  <> Extending L2TP Account Active Life"
echo -e ""
echo -e "$m=============================-$yy PPTP $m-============================$y"
echo -e ""
echo -e "* 19.add-pptp     <> Create Account PPTP"
echo -e "* 20.del-pptp       <> Delete PPTP Account"
echo -e "* 21.renew-pptp <> Extending PPTP Account Active Life"
echo -e "* 22.cek-pptp      <> Check User Login PPTP"
echo -e ""
echo -e "$m=============================-$yy SSTP $m-============================$y"
echo -e ""
echo -e "* 23.add-sstp      <> Create Account SSTP"
echo -e "* 24.del-sstp        <> Delete SSTP Account"
echo -e "* 25.renew-sstp  <> Extending SSTP Account Active Life"
echo -e "* 26.cek-sstp       <> Check User Login SSTP"
echo -e ""
echo -e "$m=============================-$yy SSR $m-=============================$y"
echo -e ""
echo -e "* 27.add-ssr         <> Create SSR Account"
echo -e "* 28.del-ssr           <> Deleting SSR Account"
echo -e "* 29.renew-ssr     <> Extending SSR Account Active Life"
echo -e "* 30.ssr                  <> Show Other SSR Menu"
echo -e ""
echo -e "$m========================-$yy SHADOWSOCKS OBFS $m-=====================$y"
echo -e ""
echo -e "* 31.add-ss           <> Creating Shadowsocks Account"
echo -e "* 32.del-ss            <> Delete Shadowsocks Account"
echo -e "* 33.renew-ss      <> Extending Shadowsocks Account Active Life"
echo -e "* 34.cek-ss            <> Check User Login Shadowsocks"
echo -e ""
echo -e "$m=============================-$yy VMESS $m-===========================$y"
echo -e ""
echo -e "* 35.add-ws          <> Create V2RAY Vmess Websocket Account"
echo -e "* 36.del-ws            <> Deleting V2RAY Vmess Websocket Account"
echo -e "* 37.renew-ws      <> Extending Vmess Account Active Life"
echo -e "* 38.cek-ws           <> Check User Login V2RAY"
echo -e "* 39.cert2vray      <> Renew Certificate V2RAY Account"
echo -e ""
echo -e "$m=============================-$yy VLESS $m-===========================$y"
echo -e ""
echo -e "* 40.add-vless      <> Create V2RAY Vless Websocket Account"
echo -e "* 41.del-vless        <> Deleting V2RAY Vless Websocket Account"
echo -e "* 42.renew-vless  <> Extending Vless Account Active Life"
echo -e "* 43.cek-ws            <> Check User Login V2RAY"
echo -e ""
echo -e "$m=============================-$yy TROJAN $m-==========================$y"
echo -e ""
echo -e "* 44.add-tr              <> Create Trojan Account"
echo -e "* 45.del-tr               <> Deleting Trojan Account"
echo -e "* 46.renew-tr         <> Extending Trojan Account Active Life"
echo -e "* 47.cek-tr              <> Check User Login Trojan"
echo -e ""
echo -e "$m=============================-$yy SYSTEM $m-==========================$y"
echo -e ""
echo -e "* 48.add-host         <> Add Or Change Subdomain Host For VPS"
echo -e "* 49.change-port   <> Change Port Of Some Service"
echo -e "* 50.autobackup    <> Autobackup Data VPS"
echo -e "* 51.backup            <> Backup Data VPS"
echo -e "* 52.restore             <> Restore Data VPS"
echo -e "* 53.wbmn               <> Webmin Menu"
echo -e "* 54.kernel-updt     <> Update To Latest Kernel"
echo -e "* 55.limit-speed      <> Limit Bandwith Speed Server"
echo -e "* 56.ram                    <> Check Usage of VPS Ram"
echo -e "* 57.reboot               <> Reboot VPS"
echo -e "* 58.speedtest         <> Speedtest VPS"
echo -e "* 59?update               <> Update To Latest Script Version"
echo -e "* 60.info                     <> Displaying System Information"
echo -e "* 61.about                 <> Info Script Auto Install"
echo -e "* 99.exit                     <> Exit From VPS "
echo -e ""
echo -e "$m================================================================$y"
echo -e " $yy ZEASTORE $y"
